### ISSUE TITLE
.find() is undefined

### ISSUE THREAD

**Issue by WonSong** [mankindsoftware/angular-isotope#22] opened 2014-08-01 22:02 UTC
![err](https://cloud.githubusercontent.com/assets/5981331/3785603/1b5bc41c-19c7-11e4-9387-1d9f240c2b2b.png)

Exception is thrown from the controller.js file line: 196

```
item = $elem.find(selector);
```

$elem is not jQuery or angular.element.

This only happens when sorting is enabled. 

Probably one of the things that was left out while removing jQuery dependency.

**Comment by nickewansmith** [comment] 2015-04-14 07:16
+1

**Comment by Schwankenson** [comment] 2015-06-07 17:26
+1
Is there a workaround?

**Comment by Schwankenson** [comment] 2015-06-07 17:39
found it: duplicate of #29
There is even a fix for it.

**Closed as completed** 2020-10-11 01:11 UTC
